docs: addition of param and result sections
inveniosoftware/invenio-jsonschemas pull request #36
Opened 2016-08-31 14:51 UTC by hachreak

* Improves documentation. (addresses #31)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

2016-09-01 06:13 UTC, alizeepace commented on invenio_jsonschemas/ext.py
>          :param path: schema path, relative to the directory when it was
where it was

2016-09-01 06:14 UTC, alizeepace commented on invenio_jsonschemas/ext.py
> +            was found in the path speficied.
the specified path

2016-09-01 06:15 UTC, alizeepace commented on invenio_jsonschemas/jsonresolver.py
> +    """JSON resolver plugin that load the schema endpoint.
loads

2016-09-01 07:21 UTC, hachreak commented
ping @jirikuncar

2016-09-05 14:52 UTC, jirikuncar commented on invenio_jsonschemas/ext.py
> -        app.config.setdefault(InvenioJSONSchemas.CONFIG_ENDPOINT,
please remove also `CONFIG_ENDPOINT = 'JSONSCHEMAS_ENDPOINT'`

2016-09-05 15:18 UTC, hachreak commented on invenio_jsonschemas/ext.py
> -        app.config.setdefault(InvenioJSONSchemas.CONFIG_ENDPOINT,
done

2016-09-07 08:56 UTC, hachreak commented
ping @jirikuncar

2016-09-15 12:24 UTC, hachreak commented
@jirikuncar  :shipit: ?

2016-09-15 14:19 UTC, jirikuncar commented on invenio_jsonschemas/views.py
> +       instance used to retrieve the schemas.
Can you check the indentation? (4 spaces)

2016-09-15 14:19 UTC, jirikuncar requested changes

2016-09-15 14:22 UTC, hachreak commented on invenio_jsonschemas/views.py
> +       instance used to retrieve the schemas.
done

2016-09-15 14:23 UTC, jirikuncar approved these changes

2016-09-16 07:31 UTC, merged