ext: warning depending on JSONSCHEMAS_HOST
inveniosoftware/invenio-jsonschemas pull request #46
Opened 2016-10-13 18:20 UTC by sulami

* Prints a warning if it is not set or set to localhost.
  (closes #33)

--

This should be fine for now, but could in future be delegated to a logging system to manage different outputs (stdout, stderr, syslog, logfiles, emails, etc.) and also severity levels.

2016-10-13 18:34 UTC, lnielsen commented on invenio_jsonschemas/ext.py
> +            print('WARNING: JSONSCHEMAS_HOST is set to {}'.format(
Thanks for the contribution. You can use

```python
app.logger.warning('JSONSCHEMAS_HOST is set to {0}'.format(...))
```

2016-10-13 18:39 UTC, sulami commented on invenio_jsonschemas/ext.py
> +            print('WARNING: JSONSCHEMAS_HOST is set to {}'.format(
Ah nice, a did a quick git grep for a logger but didn't find any, so assumed there's no logging framework in place yet

2016-10-14 07:15 UTC, jirikuncar commented
@sulami good job!

- [ ] Please add yourself to `AUTHORS`.
- [ ] Please reply if you agree to donate this (and any future) contributions to *inveniosoftware* organization under the terms of the package FLOSS license.

Thanks you!

2016-10-14 07:15 UTC, jirikuncar requested changes
AUTHORS + CLA

2016-10-14 07:17 UTC, sulami commented
> On 14 Oct 2016, at 09:15, Jiri Kuncar <notifications@github.com> wrote:
> 
> @sulami good job!
> 
> 	•  Please add yourself to AUTHORS.
> 	•  Please reply if you agree to donate this (and any future) contributions to inveniosoftware organization under the terms of the package FLOSS license.
> Thanks you!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

I’m already in AUTHORS.

And you have my permission to do anything you want with my contributions, happy to help!

2016-10-14 07:17 UTC, jirikuncar commented
@sulami sorry. I missed it :)

2016-10-14 07:17 UTC, jirikuncar approved these changes

2016-10-14 07:36 UTC, merged